// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PBlacklist;
@class PLevelInfo;
@class PLevelInfoEx;
@class PLiveInfo;
@class PLiveInfoList;
@class PUser;
@class PUserBase;
@class PUserEx;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum ELevelType

typedef GPB_ENUM(ELevelType) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  ELevelType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ///普通用户开放给所有用户
  ELevelType_User = 0,

  ///VIP为在平台内受欢迎的普通用户，并且有意向利用平台获得收益者
  ELevelType_Vip = 1,

  ///VIP+为名人明星，职业队员，游戏公司重要任务，俱乐部以及协会
  ELevelType_Vipp = 2,

  ///VO仅为电子竞技俱乐部或者公司级别
  ELevelType_Vo = 3,

  ///游客
  ELevelType_Tourist = 4,
};

GPBEnumDescriptor *ELevelType_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL ELevelType_IsValidValue(int32_t value);

#pragma mark - Enum ERightId

typedef GPB_ENUM(ERightId) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  ERightId_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ///微博展示
  ERightId_WeiboShowLeftCatalog = 0,

  ///顶部下拉
  ERightId_WeiboShowTopDropdown = 1,

  ///头像
  ERightId_WeiboShowIcon = 2,

  ///评论
  ERightId_WeiboShowComment = 3,

  ///收藏
  ERightId_WeiboShowCollect = 4,

  ///更多
  ERightId_WeiboShowMore = 5,

  ///查看详情
  ERightId_WeiboShowViewDetails = 6,

  ///微博评论
  ERightId_WeiboCommentText = 7,

  ///语音评论
  ERightId_WeiboCommentAudio = 8,

  ///微博发布
  ERightId_WeiboPostText = 9,

  ///图片贴
  ERightId_WeiboPostImage = 10,

  ///视频贴
  ERightId_WeiboPostVideo = 11,

  ///语音贴
  ERightId_WeiboPostAudio = 12,

  ///个人档案
  ERightId_PersonalRecordExternalLinks = 13,

  ///个人图标
  ERightId_PersonalRecordIcon = 14,

  ///社区 
  ERightId_PersonalRecordCommunity = 15,

  ///视频贴分类页
  ERightId_PersonalRecordVideoClassifyPage = 16,

  ///语音贴分类页
  ERightId_PersonalRecordAudioClassifyPage = 17,

  ///好友系统
  ERightId_FriendSystemRecommend = 18,

  ///搜索
  ERightId_FriendSystemSearch = 19,

  ///好友申请
  ERightId_FriendSystemFriendApplyFor = 20,

  ///通迅录
  ERightId_FriendSystemAddressBook = 21,

  ///好友
  ERightId_FriendSystemFriend = 22,

  ///我的申请
  ERightId_FriendSystemMyApplyFor = 23,

  ///其它
  ERightId_RealName = 24,
};

GPBEnumDescriptor *ERightId_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL ERightId_IsValidValue(int32_t value);

#pragma mark - AccountRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface AccountRoot : GPBRootObject
@end

#pragma mark - PUserList

typedef GPB_ENUM(PUserList_FieldNumber) {
  PUserList_FieldNumber_ListArray = 1,
};

@interface PUserList : GPBMessage

///PUser列表，最多100个
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PUser*> *listArray;
/// The number of items in @c listArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - PLiveInfo

typedef GPB_ENUM(PLiveInfo_FieldNumber) {
  PLiveInfo_FieldNumber_Website = 1,
  PLiveInfo_FieldNumber_URL = 2,
};

@interface PLiveInfo : GPBMessage

/// 网站
@property(nonatomic, readwrite, copy, null_resettable) NSString *website;

/// 直播网址
@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@end

#pragma mark - PLiveInfoList

typedef GPB_ENUM(PLiveInfoList_FieldNumber) {
  PLiveInfoList_FieldNumber_ListArray = 1,
};

@interface PLiveInfoList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PLiveInfo*> *listArray;
/// The number of items in @c listArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - PUser

typedef GPB_ENUM(PUser_FieldNumber) {
  PUser_FieldNumber_Uuid = 6,
  PUser_FieldNumber_Password = 7,
  PUser_FieldNumber_Username = 8,
  PUser_FieldNumber_Nickname = 9,
  PUser_FieldNumber_HeadImgURL = 10,
  PUser_FieldNumber_Realname = 11,
  PUser_FieldNumber_Gender = 12,
  PUser_FieldNumber_Email = 13,
  PUser_FieldNumber_Birthday = 14,
  PUser_FieldNumber_Cellphone = 15,
  PUser_FieldNumber_TimeZone = 16,
  PUser_FieldNumber_Locale = 17,
  PUser_FieldNumber_MembershipLevel = 18,
  PUser_FieldNumber_LastUpdateTime = 19,
  PUser_FieldNumber_LastLoginTime = 20,
  PUser_FieldNumber_UserResume = 21,
  PUser_FieldNumber_Link1 = 22,
  PUser_FieldNumber_Link2 = 23,
  PUser_FieldNumber_Link3 = 24,
  PUser_FieldNumber_ChatId = 25,
  PUser_FieldNumber_LevelInfo = 26,
  PUser_FieldNumber_Disable = 27,
  PUser_FieldNumber_IsAi = 28,
  PUser_FieldNumber_ForceChangePwd = 29,
  PUser_FieldNumber_AreaCode = 30,
  PUser_FieldNumber_AreaName = 31,
  PUser_FieldNumber_LiveRemind = 32,
  PUser_FieldNumber_LiveInfo = 33,
  PUser_FieldNumber_BackImage = 34,
};

/// 用户信息
@interface PUser : GPBMessage

/// 服务端标志用户的唯一id
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

/// 自有手机号码注册时输入的密码
@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

/// 用户名，唯一
@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

/// 昵称
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;

/// 头像地址
@property(nonatomic, readwrite, copy, null_resettable) NSString *headImgURL;

/// 真实姓名
@property(nonatomic, readwrite, copy, null_resettable) NSString *realname;

/// 性别，0就是女，其余的是男；人妖暂时不考虑
@property(nonatomic, readwrite) int32_t gender;

/// 邮箱地址
@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

/// 生日，格式19850101
@property(nonatomic, readwrite, copy, null_resettable) NSString *birthday;

/// 手机号
@property(nonatomic, readwrite, copy, null_resettable) NSString *cellphone;

/// 时区
@property(nonatomic, readwrite) int32_t timeZone;

/// 语言
@property(nonatomic, readwrite, copy, null_resettable) NSString *locale;

/// 会员级别
@property(nonatomic, readwrite) int32_t membershipLevel;

/// 最后更新时间TUser结构，用户/系统修改
@property(nonatomic, readwrite) int64_t lastUpdateTime;

/// 用户最后登陆时间
@property(nonatomic, readwrite) int64_t lastLoginTime;

/// 个人简介
@property(nonatomic, readwrite, copy, null_resettable) NSString *userResume;

/// 链接1
@property(nonatomic, readwrite, copy, null_resettable) NSString *link1;

/// 链接2
@property(nonatomic, readwrite, copy, null_resettable) NSString *link2;

/// 链接3
@property(nonatomic, readwrite, copy, null_resettable) NSString *link3;

/// 聊天系统分配的id
@property(nonatomic, readwrite) int64_t chatId;

/// 会员等级信息
@property(nonatomic, readwrite, strong, null_resettable) PLevelInfo *levelInfo;
/// Test to see if @c levelInfo has been set.
@property(nonatomic, readwrite) BOOL hasLevelInfo;

/// 帐户是否被禁用
@property(nonatomic, readwrite) BOOL disable;

/// 该帐户是否是机器人
@property(nonatomic, readwrite) BOOL isAi;

/// 是否登录时强制要修改密码
@property(nonatomic, readwrite) BOOL forceChangePwd;

/// 地区代码
@property(nonatomic, readwrite, copy, null_resettable) NSString *areaCode;

/// 地区名称
@property(nonatomic, readwrite, copy, null_resettable) NSString *areaName;

/// 直播提醒开关
@property(nonatomic, readwrite) BOOL liveRemind;

/// 直播提醒信息
@property(nonatomic, readwrite, strong, null_resettable) PLiveInfoList *liveInfo;
/// Test to see if @c liveInfo has been set.
@property(nonatomic, readwrite) BOOL hasLiveInfo;

/// 背景图片
@property(nonatomic, readwrite, copy, null_resettable) NSString *backImage;

@end

#pragma mark - PUserListEx

typedef GPB_ENUM(PUserListEx_FieldNumber) {
  PUserListEx_FieldNumber_ListArray = 1,
};

@interface PUserListEx : GPBMessage

///PUser列表，最多100个
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PUserEx*> *listArray;
/// The number of items in @c listArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - PUserEx

typedef GPB_ENUM(PUserEx_FieldNumber) {
  PUserEx_FieldNumber_Uuid = 6,
  PUserEx_FieldNumber_Project = 7,
  PUserEx_FieldNumber_Username = 8,
  PUserEx_FieldNumber_Password = 9,
  PUserEx_FieldNumber_Nickname = 10,
  PUserEx_FieldNumber_Realname = 11,
  PUserEx_FieldNumber_Gender = 12,
  PUserEx_FieldNumber_Birthday = 13,
  PUserEx_FieldNumber_Email = 14,
  PUserEx_FieldNumber_Cellphone = 15,
  PUserEx_FieldNumber_TimeZone = 16,
  PUserEx_FieldNumber_HeadImgURL = 17,
  PUserEx_FieldNumber_Locale = 18,
  PUserEx_FieldNumber_UserResume = 19,
  PUserEx_FieldNumber_LastUpdateTime = 20,
  PUserEx_FieldNumber_LastLoginTime = 21,
  PUserEx_FieldNumber_UserData = 22,
};

/// 扩展用户信息
@interface PUserEx : GPBMessage

/// 服务端标志用户的唯一id
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

/// 项目名称
@property(nonatomic, readwrite, copy, null_resettable) NSString *project;

/// 用户名，唯一
@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

/// 自有手机号码注册时输入的密码
@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

/// 昵称
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;

/// 真实姓名
@property(nonatomic, readwrite, copy, null_resettable) NSString *realname;

/// 性别，0就是女，其余的是男；人妖暂时不考虑
@property(nonatomic, readwrite) int32_t gender;

/// 生日，格式19850101
@property(nonatomic, readwrite, copy, null_resettable) NSString *birthday;

/// 邮箱地址
@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

/// 手机号
@property(nonatomic, readwrite, copy, null_resettable) NSString *cellphone;

/// 时区
@property(nonatomic, readwrite) int32_t timeZone;

/// 头像地址
@property(nonatomic, readwrite, copy, null_resettable) NSString *headImgURL;

/// 语言
@property(nonatomic, readwrite, copy, null_resettable) NSString *locale;

/// 简介
@property(nonatomic, readwrite, copy, null_resettable) NSString *userResume;

/// 最后更新时间TUser结构，用户/系统修改
@property(nonatomic, readwrite) int64_t lastUpdateTime;

/// 用户最后登陆时间
@property(nonatomic, readwrite) int64_t lastLoginTime;

/// 用户数据
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *userData;
/// The number of items in @c userData without causing the array to be created.
@property(nonatomic, readonly) NSUInteger userData_Count;

@end

#pragma mark - PUserBase

typedef GPB_ENUM(PUserBase_FieldNumber) {
  PUserBase_FieldNumber_Level = 2,
  PUserBase_FieldNumber_Uuid = 6,
  PUserBase_FieldNumber_UserName = 7,
  PUserBase_FieldNumber_Nickname = 8,
  PUserBase_FieldNumber_RealName = 9,
  PUserBase_FieldNumber_HeadImgURL = 10,
  PUserBase_FieldNumber_UserResume = 11,
};

/// 用户基础信息
@interface PUserBase : GPBMessage

/// 用户等级
@property(nonatomic, readwrite) int32_t level;

/// 服务端标志用户的唯一id
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

/// 用户名，唯一
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

/// 昵称
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;

/// 真实姓名
@property(nonatomic, readwrite, copy, null_resettable) NSString *realName;

/// 头像地址
@property(nonatomic, readwrite, copy, null_resettable) NSString *headImgURL;

/// 简介
@property(nonatomic, readwrite, copy, null_resettable) NSString *userResume;

@end

#pragma mark - PUserBaseList

typedef GPB_ENUM(PUserBaseList_FieldNumber) {
  PUserBaseList_FieldNumber_ListArray = 1,
};

/// 用户基础信息列表
@interface PUserBaseList : GPBMessage

///PUserBase列表，最多100个
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PUserBase*> *listArray;
/// The number of items in @c listArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - PPhoneMap

typedef GPB_ENUM(PPhoneMap_FieldNumber) {
  PPhoneMap_FieldNumber_List = 1,
};

@interface PPhoneMap : GPBMessage

///手机号：uuid
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *list;
/// The number of items in @c list without causing the array to be created.
@property(nonatomic, readonly) NSUInteger list_Count;

@end

#pragma mark - PAccount

typedef GPB_ENUM(PAccount_FieldNumber) {
  PAccount_FieldNumber_Cellphone = 2,
  PAccount_FieldNumber_Wechat = 3,
  PAccount_FieldNumber_Weibo = 4,
  PAccount_FieldNumber_Facebook = 5,
  PAccount_FieldNumber_Google = 6,
};

@interface PAccount : GPBMessage

///手机
@property(nonatomic, readwrite) BOOL cellphone;

///微信
@property(nonatomic, readwrite) BOOL wechat;

///微博
@property(nonatomic, readwrite) BOOL weibo;

///脸书
@property(nonatomic, readwrite) BOOL facebook;

///谷歌
@property(nonatomic, readwrite) BOOL google;

@end

#pragma mark - PLevelInfo

typedef GPB_ENUM(PLevelInfo_FieldNumber) {
  PLevelInfo_FieldNumber_LevelType = 1,
  PLevelInfo_FieldNumber_MapRight = 2,
};

///会员等级信息
@interface PLevelInfo : GPBMessage

@property(nonatomic, readwrite) int32_t levelType;

///会员等级权限列表
@property(nonatomic, readwrite, strong, null_resettable) GPBStringBoolDictionary *mapRight;
/// The number of items in @c mapRight without causing the array to be created.
@property(nonatomic, readonly) NSUInteger mapRight_Count;

@end

#pragma mark - PLevelInfoEx

typedef GPB_ENUM(PLevelInfoEx_FieldNumber) {
  PLevelInfoEx_FieldNumber_Uuid = 1,
  PLevelInfoEx_FieldNumber_LevelInfo = 2,
};

///会员等级扩展
@interface PLevelInfoEx : GPBMessage

///用户ID
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@property(nonatomic, readwrite, strong, null_resettable) PLevelInfo *levelInfo;
/// Test to see if @c levelInfo has been set.
@property(nonatomic, readwrite) BOOL hasLevelInfo;

@end

#pragma mark - PLevelInfos

typedef GPB_ENUM(PLevelInfos_FieldNumber) {
  PLevelInfos_FieldNumber_ListArray = 1,
  PLevelInfos_FieldNumber_FailUuidArray = 2,
};

///批量会员等级信息
@interface PLevelInfos : GPBMessage

///成功的PUuidLevelInfo信息列表
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PLevelInfoEx*> *listArray;
/// The number of items in @c listArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger listArray_Count;

///失败的uuid列表
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *failUuidArray;
/// The number of items in @c failUuidArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger failUuidArray_Count;

@end

#pragma mark - PBlacklist

typedef GPB_ENUM(PBlacklist_FieldNumber) {
  PBlacklist_FieldNumber_Id_p = 1,
  PBlacklist_FieldNumber_Val = 2,
};

///黑名单项
@interface PBlacklist : GPBMessage

///黑名单ID
@property(nonatomic, readwrite) int64_t id_p;

///黑名单值
@property(nonatomic, readwrite, copy, null_resettable) NSString *val;

@end

#pragma mark - PBlacklistList

typedef GPB_ENUM(PBlacklistList_FieldNumber) {
  PBlacklistList_FieldNumber_ListArray = 1,
};

///黑名单映射列表
@interface PBlacklistList : GPBMessage

///黑名单列表
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PBlacklist*> *listArray;
/// The number of items in @c listArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - PBlacklistVal

typedef GPB_ENUM(PBlacklistVal_FieldNumber) {
  PBlacklistVal_FieldNumber_ListArray = 1,
};

///黑名单值列表
@interface PBlacklistVal : GPBMessage

///黑名单值列表
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *listArray;
/// The number of items in @c listArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - PBlacklistID

typedef GPB_ENUM(PBlacklistID_FieldNumber) {
  PBlacklistID_FieldNumber_ListArray = 1,
};

///黑名单ID列表
@interface PBlacklistID : GPBMessage

///黑名单ID列表
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *listArray;
/// The number of items in @c listArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

#pragma mark - PBlacklistRet

typedef GPB_ENUM(PBlacklistRet_FieldNumber) {
  PBlacklistRet_FieldNumber_SuccListArray = 1,
  PBlacklistRet_FieldNumber_FailListArray = 2,
};

///黑名单列表返回
@interface PBlacklistRet : GPBMessage

///成功的列表
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *succListArray;
/// The number of items in @c succListArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger succListArray_Count;

///失败的列表
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *failListArray;
/// The number of items in @c failListArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger failListArray_Count;

@end

#pragma mark - PBlacklistExRet

typedef GPB_ENUM(PBlacklistExRet_FieldNumber) {
  PBlacklistExRet_FieldNumber_SuccListArray = 1,
  PBlacklistExRet_FieldNumber_ExistListArray = 2,
  PBlacklistExRet_FieldNumber_FailListArray = 3,
};

///黑名单列表返回
@interface PBlacklistExRet : GPBMessage

///成功的黑名单列表
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PBlacklist*> *succListArray;
/// The number of items in @c succListArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger succListArray_Count;

///已经存在的黑名单列表
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PBlacklist*> *existListArray;
/// The number of items in @c existListArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger existListArray_Count;

///失败的列表
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *failListArray;
/// The number of items in @c failListArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger failListArray_Count;

@end

#pragma mark - PBlacklistCount

typedef GPB_ENUM(PBlacklistCount_FieldNumber) {
  PBlacklistCount_FieldNumber_Count = 1,
};

///黑名单列表数量
@interface PBlacklistCount : GPBMessage

///黑名单数量
@property(nonatomic, readwrite) int64_t count;

@end

#pragma mark - PLiveRemind

typedef GPB_ENUM(PLiveRemind_FieldNumber) {
  PLiveRemind_FieldNumber_OffOn = 1,
};

///第三方直播提醒开关
@interface PLiveRemind : GPBMessage

@property(nonatomic, readwrite) BOOL offOn;

@end

#pragma mark - PAccountToken

typedef GPB_ENUM(PAccountToken_FieldNumber) {
  PAccountToken_FieldNumber_Token = 1,
};

/// 验证安全码
@interface PAccountToken : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@end

#pragma mark - PIsReadNameInfo

typedef GPB_ENUM(PIsReadNameInfo_FieldNumber) {
  PIsReadNameInfo_FieldNumber_IsReadName = 1,
};

/// 是否实名认证
@interface PIsReadNameInfo : GPBMessage

@property(nonatomic, readwrite) BOOL isReadName;

@end

#pragma mark - PAccountBaseInfo

typedef GPB_ENUM(PAccountBaseInfo_FieldNumber) {
  PAccountBaseInfo_FieldNumber_IsReadName = 1,
  PAccountBaseInfo_FieldNumber_Cellphone = 2,
};

/// 基础信息
@interface PAccountBaseInfo : GPBMessage

///是否实名认证
@property(nonatomic, readwrite) BOOL isReadName;

///手机号码
@property(nonatomic, readwrite, copy, null_resettable) NSString *cellphone;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
