// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comment.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PAudio;
@class PComment;
@class PCommentLevel;
@class PVoteUser;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - CommentRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface CommentRoot : GPBRootObject
@end

#pragma mark - PComment

typedef GPB_ENUM(PComment_FieldNumber) {
  PComment_FieldNumber_Id_p = 1,
  PComment_FieldNumber_Uuid = 2,
  PComment_FieldNumber_Nickname = 3,
  PComment_FieldNumber_HeadImgURL = 4,
  PComment_FieldNumber_AtUuid = 5,
  PComment_FieldNumber_AtNickname = 6,
  PComment_FieldNumber_IsShield = 8,
  PComment_FieldNumber_Vote = 9,
  PComment_FieldNumber_Children = 10,
  PComment_FieldNumber_Upvotes = 11,
  PComment_FieldNumber_Downvotes = 12,
  PComment_FieldNumber_CreateTime = 13,
  PComment_FieldNumber_Text = 14,
  PComment_FieldNumber_Audio = 15,
};

/// 单条评论结构详细信息
@interface PComment : GPBMessage

///评论ID
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

///评论者ID
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

///评论者昵称
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;

///评论者头像
@property(nonatomic, readwrite, copy, null_resettable) NSString *headImgURL;

///\@用户ID
@property(nonatomic, readwrite, copy, null_resettable) NSString *atUuid;

///\@用户昵称
@property(nonatomic, readwrite, copy, null_resettable) NSString *atNickname;

///保留7用于扩展
@property(nonatomic, readwrite) BOOL isShield;

///请求者是否赞过或踩过，1:赞过,-1:踩过，否则为0
@property(nonatomic, readwrite) int32_t vote;

///下一级子评论数
@property(nonatomic, readwrite) int32_t children;

///赞数
@property(nonatomic, readwrite) int32_t upvotes;

///踩数
@property(nonatomic, readwrite) int32_t downvotes;

///评论创建时间
@property(nonatomic, readwrite) int64_t createTime;

///评论文本内容
@property(nonatomic, readwrite, copy, null_resettable) NSString *text;

///语音信息
@property(nonatomic, readwrite, strong, null_resettable) PAudio *audio;
/// Test to see if @c audio has been set.
@property(nonatomic, readwrite) BOOL hasAudio;

@end

#pragma mark - PCommentLevel

typedef GPB_ENUM(PCommentLevel_FieldNumber) {
  PCommentLevel_FieldNumber_Level = 1,
  PCommentLevel_FieldNumber_Count = 2,
  PCommentLevel_FieldNumber_Interactions = 3,
  PCommentLevel_FieldNumber_CommentsArray = 4,
};

/// 某个用户等级的评论列表
@interface PCommentLevel : GPBMessage

///等级
@property(nonatomic, readwrite) int32_t level;

///评论数
@property(nonatomic, readwrite) int32_t count;

///交互数（\@次数）
@property(nonatomic, readwrite) int32_t interactions;

///评论内容
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PComment*> *commentsArray;
/// The number of items in @c commentsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger commentsArray_Count;

@end

#pragma mark - PCommentList

typedef GPB_ENUM(PCommentList_FieldNumber) {
  PCommentList_FieldNumber_CommentsArray = 1,
};

@interface PCommentList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PCommentLevel*> *commentsArray;
/// The number of items in @c commentsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger commentsArray_Count;

@end

#pragma mark - PVoteUser

typedef GPB_ENUM(PVoteUser_FieldNumber) {
  PVoteUser_FieldNumber_Uuid = 1,
  PVoteUser_FieldNumber_Nickname = 2,
  PVoteUser_FieldNumber_HeadImgURL = 3,
};

@interface PVoteUser : GPBMessage

///赞或踩的用户信息
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;

@property(nonatomic, readwrite, copy, null_resettable) NSString *headImgURL;

@end

#pragma mark - PVoteUserList

typedef GPB_ENUM(PVoteUserList_FieldNumber) {
  PVoteUserList_FieldNumber_UserArray = 1,
};

@interface PVoteUserList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PVoteUser*> *userArray;
/// The number of items in @c userArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger userArray_Count;

@end

#pragma mark - PInt32Array

typedef GPB_ENUM(PInt32Array_FieldNumber) {
  PInt32Array_FieldNumber_ArrayArray = 1,
};

@interface PInt32Array : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *arrayArray;
/// The number of items in @c arrayArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger arrayArray_Count;

@end

#pragma mark - PCommentBool

typedef GPB_ENUM(PCommentBool_FieldNumber) {
  PCommentBool_FieldNumber_IsEnable = 1,
};

@interface PCommentBool : GPBMessage

/// 是否开启评论/回复
@property(nonatomic, readwrite) BOOL isEnable;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
