// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: community.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Community.pbobjc.h"
 #import "Account.pbobjc.h"
 #import "Wallet.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - CommunityRoot

@implementation CommunityRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[AccountRoot extensionRegistry]];
    [registry addExtensions:[WalletRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - CommunityRoot_FileDescriptor

static GPBFileDescriptor *CommunityRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"common"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - PCommunityID

@implementation PCommunityID

@dynamic idArray, idArray_Count;

typedef struct PCommunityID__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *idArray;
} PCommunityID__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "idArray",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityID_FieldNumber_IdArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PCommunityID__storage_, idArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityID class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityID__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\002\000ID\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityBase

@implementation PCommunityBase

@dynamic id_p;
@dynamic name;
@dynamic headImg;
@dynamic introduce;

typedef struct PCommunityBase__storage_ {
  uint32_t _has_storage_[1];
  NSString *id_p;
  NSString *name;
  NSString *headImg;
  NSString *introduce;
} PCommunityBase__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityBase_FieldNumber_Id_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PCommunityBase__storage_, id_p),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "name",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityBase_FieldNumber_Name,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PCommunityBase__storage_, name),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "headImg",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityBase_FieldNumber_HeadImg,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PCommunityBase__storage_, headImg),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "introduce",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityBase_FieldNumber_Introduce,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PCommunityBase__storage_, introduce),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityBase class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityBase__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\004\002\000ID\000\003D\000\004G\000\005I\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityBaseList

@implementation PCommunityBaseList

@dynamic listArray, listArray_Count;

typedef struct PCommunityBaseList__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *listArray;
} PCommunityBaseList__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "listArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityBase),
        .number = PCommunityBaseList_FieldNumber_ListArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PCommunityBaseList__storage_, listArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityBaseList class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityBaseList__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\002\000List\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityInfo

@implementation PCommunityInfo

@dynamic status;
@dynamic membership;
@dynamic id_p;
@dynamic name;
@dynamic headImg;
@dynamic backgroundImg;
@dynamic introduce;
@dynamic ownerUuid;
@dynamic ownerName;
@dynamic memberCount;
@dynamic forumPostCount;
@dynamic noticePostCount;

typedef struct PCommunityInfo__storage_ {
  uint32_t _has_storage_[1];
  int32_t status;
  int32_t membership;
  int32_t memberCount;
  int32_t forumPostCount;
  int32_t noticePostCount;
  NSString *id_p;
  NSString *name;
  NSString *headImg;
  NSString *backgroundImg;
  NSString *introduce;
  NSString *ownerUuid;
  NSString *ownerName;
} PCommunityInfo__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "status",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityInfo_FieldNumber_Status,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PCommunityInfo__storage_, status),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "membership",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityInfo_FieldNumber_Membership,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PCommunityInfo__storage_, membership),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityInfo_FieldNumber_Id_p,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PCommunityInfo__storage_, id_p),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "name",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityInfo_FieldNumber_Name,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PCommunityInfo__storage_, name),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "headImg",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityInfo_FieldNumber_HeadImg,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(PCommunityInfo__storage_, headImg),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "backgroundImg",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityInfo_FieldNumber_BackgroundImg,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(PCommunityInfo__storage_, backgroundImg),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "introduce",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityInfo_FieldNumber_Introduce,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(PCommunityInfo__storage_, introduce),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "ownerUuid",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityInfo_FieldNumber_OwnerUuid,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(PCommunityInfo__storage_, ownerUuid),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "ownerName",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityInfo_FieldNumber_OwnerName,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(PCommunityInfo__storage_, ownerName),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "memberCount",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityInfo_FieldNumber_MemberCount,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(PCommunityInfo__storage_, memberCount),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "forumPostCount",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityInfo_FieldNumber_ForumPostCount,
        .hasIndex = 10,
        .offset = (uint32_t)offsetof(PCommunityInfo__storage_, forumPostCount),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "noticePostCount",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityInfo_FieldNumber_NoticePostCount,
        .hasIndex = 11,
        .offset = (uint32_t)offsetof(PCommunityInfo__storage_, noticePostCount),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityInfo class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityInfo__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\014\002F\000\003J\000\004\000ID\000\005D\000\006G\000\007M\000\010I\000\tFc\000\nI\000\013K\000\014N\000\rO\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityMe

@implementation PCommunityMe

@dynamic hasInfo, info;
@dynamic hasList, list;

typedef struct PCommunityMe__storage_ {
  uint32_t _has_storage_[1];
  PCommunityInfo *info;
  PCommunityBaseList *list;
} PCommunityMe__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "info",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityInfo),
        .number = PCommunityMe_FieldNumber_Info,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PCommunityMe__storage_, info),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "list",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityBaseList),
        .number = PCommunityMe_FieldNumber_List,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PCommunityMe__storage_, list),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityMe class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityMe__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\002D\000\003D\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityResource

@implementation PCommunityResource

@dynamic type;
@dynamic name;
@dynamic URL;
@dynamic size;

typedef struct PCommunityResource__storage_ {
  uint32_t _has_storage_[1];
  NSString *type;
  NSString *name;
  NSString *URL;
  NSString *size;
} PCommunityResource__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityResource_FieldNumber_Type,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PCommunityResource__storage_, type),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "name",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityResource_FieldNumber_Name,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PCommunityResource__storage_, name),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "URL",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityResource_FieldNumber_URL,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PCommunityResource__storage_, URL),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "size",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityResource_FieldNumber_Size,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PCommunityResource__storage_, size),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityResource class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityResource__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\004\002D\000\003D\000\004\003\000\005D\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityResourceList

@implementation PCommunityResourceList

@dynamic resourceArray, resourceArray_Count;

typedef struct PCommunityResourceList__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *resourceArray;
} PCommunityResourceList__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "resourceArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityResource),
        .number = PCommunityResourceList_FieldNumber_ResourceArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PCommunityResourceList__storage_, resourceArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityResourceList class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityResourceList__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\002\000Resource\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityPostUpload

@implementation PCommunityPostUpload

@dynamic title;
@dynamic subType;
@dynamic bannerImg;
@dynamic hasResourcesList, resourcesList;

typedef struct PCommunityPostUpload__storage_ {
  uint32_t _has_storage_[1];
  NSString *title;
  NSString *subType;
  NSString *bannerImg;
  PCommunityResourceList *resourcesList;
} PCommunityPostUpload__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "title",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityPostUpload_FieldNumber_Title,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PCommunityPostUpload__storage_, title),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "subType",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityPostUpload_FieldNumber_SubType,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PCommunityPostUpload__storage_, subType),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "bannerImg",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityPostUpload_FieldNumber_BannerImg,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PCommunityPostUpload__storage_, bannerImg),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "resourcesList",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityResourceList),
        .number = PCommunityPostUpload_FieldNumber_ResourcesList,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PCommunityPostUpload__storage_, resourcesList),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityPostUpload class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityPostUpload__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\004\002E\000\003G\000\004I\000\nM\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityRedpacketUpload

@implementation PCommunityRedpacketUpload

@dynamic hasPost, post;
@dynamic hasRedpacket, redpacket;

typedef struct PCommunityRedpacketUpload__storage_ {
  uint32_t _has_storage_[1];
  PCommunityPostUpload *post;
  PSendRedPacket *redpacket;
} PCommunityRedpacketUpload__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "post",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityPostUpload),
        .number = PCommunityRedpacketUpload_FieldNumber_Post,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PCommunityRedpacketUpload__storage_, post),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "redpacket",
        .dataTypeSpecific.className = GPBStringifySymbol(PSendRedPacket),
        .number = PCommunityRedpacketUpload_FieldNumber_Redpacket,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PCommunityRedpacketUpload__storage_, redpacket),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityRedpacketUpload class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityRedpacketUpload__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\002D\000\003I\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityPostInfo

@implementation PCommunityPostInfo

@dynamic id_p;
@dynamic type;
@dynamic subType;
@dynamic time;
@dynamic title;
@dynamic isView;
@dynamic viewCount;
@dynamic commentCount;
@dynamic hasUser, user;
@dynamic hasResourcesList, resourcesList;
@dynamic hasRedpacket, redpacket;
@dynamic hasBannerImg, bannerImg;
@dynamic isTop;

typedef struct PCommunityPostInfo__storage_ {
  uint32_t _has_storage_[1];
  NSString *id_p;
  NSString *type;
  NSString *subType;
  NSString *title;
  PUserBase *user;
  PCommunityResourceList *resourcesList;
  PRedPacketInfo *redpacket;
  PCommunityResource *bannerImg;
  int64_t time;
  int64_t viewCount;
  int64_t commentCount;
} PCommunityPostInfo__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityPostInfo_FieldNumber_Id_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PCommunityPostInfo__storage_, id_p),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityPostInfo_FieldNumber_Type,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PCommunityPostInfo__storage_, type),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "subType",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityPostInfo_FieldNumber_SubType,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PCommunityPostInfo__storage_, subType),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "time",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityPostInfo_FieldNumber_Time,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PCommunityPostInfo__storage_, time),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "title",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityPostInfo_FieldNumber_Title,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(PCommunityPostInfo__storage_, title),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "isView",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityPostInfo_FieldNumber_IsView,
        .hasIndex = 5,
        .offset = 6,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "viewCount",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityPostInfo_FieldNumber_ViewCount,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(PCommunityPostInfo__storage_, viewCount),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "commentCount",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityPostInfo_FieldNumber_CommentCount,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(PCommunityPostInfo__storage_, commentCount),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "user",
        .dataTypeSpecific.className = GPBStringifySymbol(PUserBase),
        .number = PCommunityPostInfo_FieldNumber_User,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(PCommunityPostInfo__storage_, user),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "resourcesList",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityResourceList),
        .number = PCommunityPostInfo_FieldNumber_ResourcesList,
        .hasIndex = 10,
        .offset = (uint32_t)offsetof(PCommunityPostInfo__storage_, resourcesList),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "redpacket",
        .dataTypeSpecific.className = GPBStringifySymbol(PRedPacketInfo),
        .number = PCommunityPostInfo_FieldNumber_Redpacket,
        .hasIndex = 11,
        .offset = (uint32_t)offsetof(PCommunityPostInfo__storage_, redpacket),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "bannerImg",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityResource),
        .number = PCommunityPostInfo_FieldNumber_BannerImg,
        .hasIndex = 12,
        .offset = (uint32_t)offsetof(PCommunityPostInfo__storage_, bannerImg),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "isTop",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityPostInfo_FieldNumber_IsTop,
        .hasIndex = 13,
        .offset = 14,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeBool,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityPostInfo class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityPostInfo__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\r\002\000ID\000\003D\000\004G\000\005D\000\006E\000\007F\000\010I\000\tL\000\nD\000\013M\000\014I\000\rI\000\016"
        "E\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityPostList

@implementation PCommunityPostList

@dynamic postInfoArray, postInfoArray_Count;

typedef struct PCommunityPostList__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *postInfoArray;
} PCommunityPostList__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "postInfoArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityPostInfo),
        .number = PCommunityPostList_FieldNumber_PostInfoArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PCommunityPostList__storage_, postInfoArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityPostList class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityPostList__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\002\000PostInfo\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityFlagPostList

@implementation PCommunityFlagPostList

@dynamic flagCountArray, flagCountArray_Count;
@dynamic postInfoArray, postInfoArray_Count;

typedef struct PCommunityFlagPostList__storage_ {
  uint32_t _has_storage_[1];
  GPBInt32Array *flagCountArray;
  NSMutableArray *postInfoArray;
} PCommunityFlagPostList__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "flagCountArray",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityFlagPostList_FieldNumber_FlagCountArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PCommunityFlagPostList__storage_, flagCountArray),
        .flags = GPBFieldRepeated | GPBFieldPacked | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "postInfoArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityPostInfo),
        .number = PCommunityFlagPostList_FieldNumber_PostInfoArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PCommunityFlagPostList__storage_, postInfoArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityFlagPostList class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityFlagPostList__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\002\000FlagCount\000\003\000PostInfo\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityHome

@implementation PCommunityHome

@dynamic hasInfo, info;
@dynamic hasList, list;

typedef struct PCommunityHome__storage_ {
  uint32_t _has_storage_[1];
  PCommunityInfo *info;
  PCommunityPostList *list;
} PCommunityHome__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "info",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityInfo),
        .number = PCommunityHome_FieldNumber_Info,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PCommunityHome__storage_, info),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "list",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityPostList),
        .number = PCommunityHome_FieldNumber_List,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PCommunityHome__storage_, list),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityHome class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityHome__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\002D\000\003D\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityPostComment

@implementation PCommunityPostComment

@dynamic quoteId;
@dynamic content;

typedef struct PCommunityPostComment__storage_ {
  uint32_t _has_storage_[1];
  NSString *quoteId;
  NSString *content;
} PCommunityPostComment__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "quoteId",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityPostComment_FieldNumber_QuoteId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PCommunityPostComment__storage_, quoteId),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "content",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityPostComment_FieldNumber_Content,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PCommunityPostComment__storage_, content),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityPostComment class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityPostComment__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\002FA\000\003G\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityCommentInfo

@implementation PCommunityCommentInfo

@dynamic floor;
@dynamic upVote;
@dynamic downVote;
@dynamic status;
@dynamic id_p;
@dynamic time;
@dynamic content;
@dynamic hasUser, user;
@dynamic hasQuoteInfo, quoteInfo;
@dynamic isDelete;

typedef struct PCommunityCommentInfo__storage_ {
  uint32_t _has_storage_[1];
  int32_t floor;
  int32_t upVote;
  int32_t downVote;
  int32_t status;
  NSString *id_p;
  NSString *content;
  PUserBase *user;
  PCommunityCommentInfo *quoteInfo;
  int64_t time;
} PCommunityCommentInfo__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "floor",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityCommentInfo_FieldNumber_Floor,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PCommunityCommentInfo__storage_, floor),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "upVote",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityCommentInfo_FieldNumber_UpVote,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PCommunityCommentInfo__storage_, upVote),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "downVote",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityCommentInfo_FieldNumber_DownVote,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PCommunityCommentInfo__storage_, downVote),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "status",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityCommentInfo_FieldNumber_Status,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PCommunityCommentInfo__storage_, status),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityCommentInfo_FieldNumber_Id_p,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(PCommunityCommentInfo__storage_, id_p),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "time",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityCommentInfo_FieldNumber_Time,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(PCommunityCommentInfo__storage_, time),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "content",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityCommentInfo_FieldNumber_Content,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(PCommunityCommentInfo__storage_, content),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "user",
        .dataTypeSpecific.className = GPBStringifySymbol(PUserBase),
        .number = PCommunityCommentInfo_FieldNumber_User,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(PCommunityCommentInfo__storage_, user),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "quoteInfo",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityCommentInfo),
        .number = PCommunityCommentInfo_FieldNumber_QuoteInfo,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(PCommunityCommentInfo__storage_, quoteInfo),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "isDelete",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityCommentInfo_FieldNumber_IsDelete,
        .hasIndex = 9,
        .offset = 10,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeBool,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityCommentInfo class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityCommentInfo__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\n\002E\000\003F\000\004H\000\005F\000\006\000ID\000\007D\000\010G\000\tD\000\nI\000\013H\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityCommentInfoList

@implementation PCommunityCommentInfoList

@dynamic listArray, listArray_Count;

typedef struct PCommunityCommentInfoList__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *listArray;
} PCommunityCommentInfoList__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "listArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityCommentInfo),
        .number = PCommunityCommentInfoList_FieldNumber_ListArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PCommunityCommentInfoList__storage_, listArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityCommentInfoList class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityCommentInfoList__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\002\000List\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityMailUpload

@implementation PCommunityMailUpload

@dynamic content;
@dynamic isView;
@dynamic hasResourcesList, resourcesList;

typedef struct PCommunityMailUpload__storage_ {
  uint32_t _has_storage_[1];
  NSString *content;
  PCommunityResourceList *resourcesList;
} PCommunityMailUpload__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "content",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityMailUpload_FieldNumber_Content,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PCommunityMailUpload__storage_, content),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "isView",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityMailUpload_FieldNumber_IsView,
        .hasIndex = 1,
        .offset = 2,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "resourcesList",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityResourceList),
        .number = PCommunityMailUpload_FieldNumber_ResourcesList,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PCommunityMailUpload__storage_, resourcesList),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityMailUpload class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityMailUpload__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\003\002G\000\003F\000\nM\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityMailInfo

@implementation PCommunityMailInfo

@dynamic id_p;
@dynamic replyId;
@dynamic time;
@dynamic isView;
@dynamic content;
@dynamic hasUser, user;
@dynamic hasResourcesList, resourcesList;
@dynamic hasReplyInfo, replyInfo;

typedef struct PCommunityMailInfo__storage_ {
  uint32_t _has_storage_[1];
  NSString *replyId;
  NSString *content;
  PUserBase *user;
  PCommunityResourceList *resourcesList;
  PCommunityMailInfo *replyInfo;
  int64_t id_p;
  int64_t time;
} PCommunityMailInfo__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityMailInfo_FieldNumber_Id_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PCommunityMailInfo__storage_, id_p),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "replyId",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityMailInfo_FieldNumber_ReplyId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PCommunityMailInfo__storage_, replyId),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "time",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityMailInfo_FieldNumber_Time,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PCommunityMailInfo__storage_, time),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "isView",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityMailInfo_FieldNumber_IsView,
        .hasIndex = 3,
        .offset = 4,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "content",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityMailInfo_FieldNumber_Content,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(PCommunityMailInfo__storage_, content),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "user",
        .dataTypeSpecific.className = GPBStringifySymbol(PUserBase),
        .number = PCommunityMailInfo_FieldNumber_User,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(PCommunityMailInfo__storage_, user),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "resourcesList",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityResourceList),
        .number = PCommunityMailInfo_FieldNumber_ResourcesList,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(PCommunityMailInfo__storage_, resourcesList),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "replyInfo",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityMailInfo),
        .number = PCommunityMailInfo_FieldNumber_ReplyInfo,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(PCommunityMailInfo__storage_, replyInfo),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityMailInfo class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityMailInfo__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\010\002\000ID\000\003FA\000\004D\000\005F\000\006G\000\007D\000\010M\000\tI\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityMailList

@implementation PCommunityMailList

@dynamic unread;
@dynamic mailInfoArray, mailInfoArray_Count;

typedef struct PCommunityMailList__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *mailInfoArray;
  int64_t unread;
} PCommunityMailList__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "unread",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityMailList_FieldNumber_Unread,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PCommunityMailList__storage_, unread),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "mailInfoArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityMailInfo),
        .number = PCommunityMailList_FieldNumber_MailInfoArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PCommunityMailList__storage_, mailInfoArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityMailList class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityMailList__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\002F\000\003\000MailInfo\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityMember

@implementation PCommunityMember

@dynamic hasUser, user;
@dynamic isFriend;
@dynamic isFollow;
@dynamic isManager;

typedef struct PCommunityMember__storage_ {
  uint32_t _has_storage_[1];
  int32_t isFriend;
  int32_t isFollow;
  int32_t isManager;
  PUserBase *user;
} PCommunityMember__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "user",
        .dataTypeSpecific.className = GPBStringifySymbol(PUserBase),
        .number = PCommunityMember_FieldNumber_User,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PCommunityMember__storage_, user),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "isFriend",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityMember_FieldNumber_IsFriend,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PCommunityMember__storage_, isFriend),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "isFollow",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityMember_FieldNumber_IsFollow,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PCommunityMember__storage_, isFollow),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "isManager",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityMember_FieldNumber_IsManager,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PCommunityMember__storage_, isManager),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityMember class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityMember__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\004\002D\000\003H\000\004H\000\005I\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityMemberList

@implementation PCommunityMemberList

@dynamic listArray, listArray_Count;

typedef struct PCommunityMemberList__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *listArray;
} PCommunityMemberList__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "listArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityMember),
        .number = PCommunityMemberList_FieldNumber_ListArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PCommunityMemberList__storage_, listArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityMemberList class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityMemberList__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\002\000List\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityFriend

@implementation PCommunityFriend

@dynamic hasUser, user;
@dynamic status;
@dynamic membership;

typedef struct PCommunityFriend__storage_ {
  uint32_t _has_storage_[1];
  int32_t status;
  int32_t membership;
  PUserBase *user;
} PCommunityFriend__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "user",
        .dataTypeSpecific.className = GPBStringifySymbol(PUserBase),
        .number = PCommunityFriend_FieldNumber_User,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PCommunityFriend__storage_, user),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "status",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityFriend_FieldNumber_Status,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PCommunityFriend__storage_, status),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "membership",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityFriend_FieldNumber_Membership,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PCommunityFriend__storage_, membership),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityFriend class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityFriend__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\003\002D\000\003F\000\004J\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityFriendList

@implementation PCommunityFriendList

@dynamic listArray, listArray_Count;

typedef struct PCommunityFriendList__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *listArray;
} PCommunityFriendList__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "listArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityFriend),
        .number = PCommunityFriendList_FieldNumber_ListArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PCommunityFriendList__storage_, listArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityFriendList class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityFriendList__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\002\000List\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityFlag

@implementation PCommunityFlag

@dynamic flagId;
@dynamic flagType;
@dynamic flagCount;
@dynamic flagTime;
@dynamic postId;
@dynamic commentId;
@dynamic title;
@dynamic content;

typedef struct PCommunityFlag__storage_ {
  uint32_t _has_storage_[1];
  int32_t flagType;
  int32_t flagCount;
  NSString *flagId;
  NSString *postId;
  NSString *commentId;
  NSString *title;
  NSString *content;
  int64_t flagTime;
} PCommunityFlag__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "flagId",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityFlag_FieldNumber_FlagId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PCommunityFlag__storage_, flagId),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "flagType",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityFlag_FieldNumber_FlagType,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PCommunityFlag__storage_, flagType),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "flagCount",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityFlag_FieldNumber_FlagCount,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PCommunityFlag__storage_, flagCount),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "flagTime",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityFlag_FieldNumber_FlagTime,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PCommunityFlag__storage_, flagTime),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "postId",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityFlag_FieldNumber_PostId,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(PCommunityFlag__storage_, postId),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "commentId",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityFlag_FieldNumber_CommentId,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(PCommunityFlag__storage_, commentId),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "title",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityFlag_FieldNumber_Title,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(PCommunityFlag__storage_, title),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "content",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityFlag_FieldNumber_Content,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(PCommunityFlag__storage_, content),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityFlag class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityFlag__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\010\002EA\000\003H\000\004I\000\005H\000\006EA\000\007HA\000\tE\000\nG\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityFlagList

@implementation PCommunityFlagList

@dynamic listArray, listArray_Count;

typedef struct PCommunityFlagList__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *listArray;
} PCommunityFlagList__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "listArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityFlag),
        .number = PCommunityFlagList_FieldNumber_ListArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PCommunityFlagList__storage_, listArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityFlagList class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityFlagList__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\002\000List\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityNotification

@implementation PCommunityNotification

@dynamic isView;
@dynamic type;
@dynamic id_p;
@dynamic time;
@dynamic content;
@dynamic jumpId;
@dynamic jumpExId;
@dynamic hasUser, user;

typedef struct PCommunityNotification__storage_ {
  uint32_t _has_storage_[1];
  int32_t type;
  NSString *content;
  NSString *jumpId;
  NSString *jumpExId;
  PUserBase *user;
  int64_t id_p;
  int64_t time;
} PCommunityNotification__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "isView",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityNotification_FieldNumber_IsView,
        .hasIndex = 0,
        .offset = 1,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityNotification_FieldNumber_Type,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PCommunityNotification__storage_, type),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityNotification_FieldNumber_Id_p,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PCommunityNotification__storage_, id_p),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "time",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityNotification_FieldNumber_Time,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(PCommunityNotification__storage_, time),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "content",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityNotification_FieldNumber_Content,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(PCommunityNotification__storage_, content),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "jumpId",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityNotification_FieldNumber_JumpId,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(PCommunityNotification__storage_, jumpId),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "jumpExId",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityNotification_FieldNumber_JumpExId,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(PCommunityNotification__storage_, jumpExId),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "user",
        .dataTypeSpecific.className = GPBStringifySymbol(PUserBase),
        .number = PCommunityNotification_FieldNumber_User,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(PCommunityNotification__storage_, user),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityNotification class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityNotification__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\010\002F\000\003D\000\004\000ID\000\005D\000\006G\000\007EA\000\010GA\000\tD\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityNotificationList

@implementation PCommunityNotificationList

@dynamic listArray, listArray_Count;

typedef struct PCommunityNotificationList__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *listArray;
} PCommunityNotificationList__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "listArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PCommunityNotification),
        .number = PCommunityNotificationList_FieldNumber_ListArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PCommunityNotificationList__storage_, listArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityNotificationList class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityNotificationList__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\002\000List\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PCommunityNotificationUnRead

@implementation PCommunityNotificationUnRead

@dynamic unread;

typedef struct PCommunityNotificationUnRead__storage_ {
  uint32_t _has_storage_[1];
  int64_t unread;
} PCommunityNotificationUnRead__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "unread",
        .dataTypeSpecific.className = NULL,
        .number = PCommunityNotificationUnRead_FieldNumber_Unread,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PCommunityNotificationUnRead__storage_, unread),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PCommunityNotificationUnRead class]
                                     rootClass:[CommunityRoot class]
                                          file:CommunityRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PCommunityNotificationUnRead__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\002F\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
