// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contact.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PContactLinkInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ContactRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface ContactRoot : GPBRootObject
@end

#pragma mark - PContactLinkInfo

typedef GPB_ENUM(PContactLinkInfo_FieldNumber) {
  PContactLinkInfo_FieldNumber_Uuid = 1,
  PContactLinkInfo_FieldNumber_Mobile = 2,
  PContactLinkInfo_FieldNumber_NickName = 3,
  PContactLinkInfo_FieldNumber_HasLink = 4,
};

@interface PContactLinkInfo : GPBMessage

/// 通讯录联系人的uuid
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

/// 通讯录联系人的手机号码
@property(nonatomic, readwrite, copy, null_resettable) NSString *mobile;

/// 通讯录联系人的昵称
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickName;

/// 通讯录联系人是否已经加入好友。取值：1--已加好友，2--可以加好友，3--不能加好友，4--对方等级高(不能加，也不能邀请)
@property(nonatomic, readwrite, copy, null_resettable) NSString *hasLink;

@end

#pragma mark - PContactLinkInfoList

typedef GPB_ENUM(PContactLinkInfoList_FieldNumber) {
  PContactLinkInfoList_FieldNumber_ContactUsersArray = 1,
  PContactLinkInfoList_FieldNumber_TotalCount = 2,
};

/// 下载通讯录好友关系
@interface PContactLinkInfoList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PContactLinkInfo*> *contactUsersArray;
/// The number of items in @c contactUsersArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger contactUsersArray_Count;

/// 总记录数
@property(nonatomic, readwrite, copy, null_resettable) NSString *totalCount;

@end

#pragma mark - PLastModifyInfo

typedef GPB_ENUM(PLastModifyInfo_FieldNumber) {
  PLastModifyInfo_FieldNumber_DevSerial = 1,
  PLastModifyInfo_FieldNumber_ModifyTime = 2,
};

/// 访问设备的最后修改时间
@interface PLastModifyInfo : GPBMessage

/// 设备串行号
@property(nonatomic, readwrite, copy, null_resettable) NSString *devSerial;

/// 最后时间
@property(nonatomic, readwrite, copy, null_resettable) NSString *modifyTime;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
