// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netdisk.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Netdisk.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - NetdiskRoot

@implementation NetdiskRoot

@end

#pragma mark - NetdiskRoot_FileDescriptor

static GPBFileDescriptor *NetdiskRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"common"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - PNetFileInfo

@implementation PNetFileInfo

@dynamic objectKey;
@dynamic extension;
@dynamic fileSize;
@dynamic fileDigest;
@dynamic createTime;
@dynamic transferFlag;
@dynamic shareFlag;
@dynamic conserveFlag;
@dynamic title;
@dynamic description_p;
@dynamic remark;

typedef struct PNetFileInfo__storage_ {
  uint32_t _has_storage_[1];
  NSString *objectKey;
  NSString *extension;
  NSString *fileSize;
  NSString *fileDigest;
  NSString *createTime;
  NSString *transferFlag;
  NSString *shareFlag;
  NSString *conserveFlag;
  NSString *title;
  NSString *description_p;
  NSString *remark;
} PNetFileInfo__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "objectKey",
        .dataTypeSpecific.className = NULL,
        .number = PNetFileInfo_FieldNumber_ObjectKey,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PNetFileInfo__storage_, objectKey),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "extension",
        .dataTypeSpecific.className = NULL,
        .number = PNetFileInfo_FieldNumber_Extension,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PNetFileInfo__storage_, extension),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "fileSize",
        .dataTypeSpecific.className = NULL,
        .number = PNetFileInfo_FieldNumber_FileSize,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PNetFileInfo__storage_, fileSize),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "fileDigest",
        .dataTypeSpecific.className = NULL,
        .number = PNetFileInfo_FieldNumber_FileDigest,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PNetFileInfo__storage_, fileDigest),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "createTime",
        .dataTypeSpecific.className = NULL,
        .number = PNetFileInfo_FieldNumber_CreateTime,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(PNetFileInfo__storage_, createTime),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "transferFlag",
        .dataTypeSpecific.className = NULL,
        .number = PNetFileInfo_FieldNumber_TransferFlag,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(PNetFileInfo__storage_, transferFlag),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "shareFlag",
        .dataTypeSpecific.className = NULL,
        .number = PNetFileInfo_FieldNumber_ShareFlag,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(PNetFileInfo__storage_, shareFlag),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "conserveFlag",
        .dataTypeSpecific.className = NULL,
        .number = PNetFileInfo_FieldNumber_ConserveFlag,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(PNetFileInfo__storage_, conserveFlag),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "title",
        .dataTypeSpecific.className = NULL,
        .number = PNetFileInfo_FieldNumber_Title,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(PNetFileInfo__storage_, title),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "description_p",
        .dataTypeSpecific.className = NULL,
        .number = PNetFileInfo_FieldNumber_Description_p,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(PNetFileInfo__storage_, description_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "remark",
        .dataTypeSpecific.className = NULL,
        .number = PNetFileInfo_FieldNumber_Remark,
        .hasIndex = 10,
        .offset = (uint32_t)offsetof(PNetFileInfo__storage_, remark),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PNetFileInfo class]
                                     rootClass:[NetdiskRoot class]
                                          file:NetdiskRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PNetFileInfo__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\007\001\t\000\003\010\000\004\n\000\005\n\000\006\014\000\007\t\000\010\014\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PListNetFileInfo

@implementation PListNetFileInfo

@dynamic netFilesArray, netFilesArray_Count;
@dynamic diskSize;

typedef struct PListNetFileInfo__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *netFilesArray;
  NSString *diskSize;
} PListNetFileInfo__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "netFilesArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PNetFileInfo),
        .number = PListNetFileInfo_FieldNumber_NetFilesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PListNetFileInfo__storage_, netFilesArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "diskSize",
        .dataTypeSpecific.className = NULL,
        .number = PListNetFileInfo_FieldNumber_DiskSize,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PListNetFileInfo__storage_, diskSize),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PListNetFileInfo class]
                                     rootClass:[NetdiskRoot class]
                                          file:NetdiskRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PListNetFileInfo__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001\000netFiles\000\002H\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PBuildUrlInfo

@implementation PBuildUrlInfo

@dynamic publicURL;

typedef struct PBuildUrlInfo__storage_ {
  uint32_t _has_storage_[1];
  NSString *publicURL;
} PBuildUrlInfo__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "publicURL",
        .dataTypeSpecific.className = NULL,
        .number = PBuildUrlInfo_FieldNumber_PublicURL,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PBuildUrlInfo__storage_, publicURL),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PBuildUrlInfo class]
                                     rootClass:[NetdiskRoot class]
                                          file:NetdiskRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PBuildUrlInfo__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001\t\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
