// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oss.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Oss.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - OssRoot

@implementation OssRoot

@end

#pragma mark - OssRoot_FileDescriptor

static GPBFileDescriptor *OssRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"common"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - PSts

@implementation PSts

@dynamic accessKeyId;
@dynamic accessKeySecret;
@dynamic securityToken;
@dynamic expiration;

typedef struct PSts__storage_ {
  uint32_t _has_storage_[1];
  NSString *accessKeyId;
  NSString *accessKeySecret;
  NSString *securityToken;
  NSString *expiration;
} PSts__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "accessKeyId",
        .dataTypeSpecific.className = NULL,
        .number = PSts_FieldNumber_AccessKeyId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PSts__storage_, accessKeyId),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "accessKeySecret",
        .dataTypeSpecific.className = NULL,
        .number = PSts_FieldNumber_AccessKeySecret,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PSts__storage_, accessKeySecret),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "securityToken",
        .dataTypeSpecific.className = NULL,
        .number = PSts_FieldNumber_SecurityToken,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PSts__storage_, securityToken),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "expiration",
        .dataTypeSpecific.className = NULL,
        .number = PSts_FieldNumber_Expiration,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PSts__storage_, expiration),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PSts class]
                                     rootClass:[OssRoot class]
                                          file:OssRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PSts__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\003\001\013\000\002\017\000\003\r\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PUpload

@implementation PUpload

@dynamic exists;
@dynamic URL;
@dynamic headersArray, headersArray_Count;
@dynamic objectKey;

typedef struct PUpload__storage_ {
  uint32_t _has_storage_[1];
  NSString *URL;
  NSMutableArray *headersArray;
  NSString *objectKey;
} PUpload__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "exists",
        .dataTypeSpecific.className = NULL,
        .number = PUpload_FieldNumber_Exists,
        .hasIndex = 0,
        .offset = 1,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "URL",
        .dataTypeSpecific.className = NULL,
        .number = PUpload_FieldNumber_URL,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PUpload__storage_, URL),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "headersArray",
        .dataTypeSpecific.className = NULL,
        .number = PUpload_FieldNumber_HeadersArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PUpload__storage_, headersArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "objectKey",
        .dataTypeSpecific.className = NULL,
        .number = PUpload_FieldNumber_ObjectKey,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PUpload__storage_, objectKey),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PUpload class]
                                     rootClass:[OssRoot class]
                                          file:OssRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PUpload__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\002!!!\000\004\t\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PDownload

@implementation PDownload

@dynamic URL;
@dynamic thumb;

typedef struct PDownload__storage_ {
  uint32_t _has_storage_[1];
  NSString *URL;
  NSString *thumb;
} PDownload__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "URL",
        .dataTypeSpecific.className = NULL,
        .number = PDownload_FieldNumber_URL,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PDownload__storage_, URL),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "thumb",
        .dataTypeSpecific.className = NULL,
        .number = PDownload_FieldNumber_Thumb,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PDownload__storage_, thumb),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PDownload class]
                                     rootClass:[OssRoot class]
                                          file:OssRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PDownload__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001!!!\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PUploadArray

@implementation PUploadArray

@dynamic uploadsArray, uploadsArray_Count;

typedef struct PUploadArray__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *uploadsArray;
} PUploadArray__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "uploadsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PUpload),
        .number = PUploadArray_FieldNumber_UploadsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PUploadArray__storage_, uploadsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PUploadArray class]
                                     rootClass:[OssRoot class]
                                          file:OssRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PUploadArray__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PDownloadArray

@implementation PDownloadArray

@dynamic downloadsArray, downloadsArray_Count;

typedef struct PDownloadArray__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *downloadsArray;
} PDownloadArray__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "downloadsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PDownload),
        .number = PDownloadArray_FieldNumber_DownloadsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PDownloadArray__storage_, downloadsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PDownloadArray class]
                                     rootClass:[OssRoot class]
                                          file:OssRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PDownloadArray__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PFileInfo

@implementation PFileInfo

@dynamic digest;
@dynamic length;
@dynamic extension;

typedef struct PFileInfo__storage_ {
  uint32_t _has_storage_[1];
  int32_t length;
  NSString *digest;
  NSString *extension;
} PFileInfo__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "digest",
        .dataTypeSpecific.className = NULL,
        .number = PFileInfo_FieldNumber_Digest,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PFileInfo__storage_, digest),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "length",
        .dataTypeSpecific.className = NULL,
        .number = PFileInfo_FieldNumber_Length,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PFileInfo__storage_, length),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "extension",
        .dataTypeSpecific.className = NULL,
        .number = PFileInfo_FieldNumber_Extension,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PFileInfo__storage_, extension),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PFileInfo class]
                                     rootClass:[OssRoot class]
                                          file:OssRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PFileInfo__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PFileInfoArray

@implementation PFileInfoArray

@dynamic fileInfosArray, fileInfosArray_Count;

typedef struct PFileInfoArray__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *fileInfosArray;
} PFileInfoArray__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "fileInfosArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PFileInfo),
        .number = PFileInfoArray_FieldNumber_FileInfosArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PFileInfoArray__storage_, fileInfosArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PFileInfoArray class]
                                     rootClass:[OssRoot class]
                                          file:OssRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PFileInfoArray__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001\000fileInfos\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
