// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: social.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PSearchUser;
@class PUser;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SocialRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface SocialRoot : GPBRootObject
@end

#pragma mark - PFriendCount

typedef GPB_ENUM(PFriendCount_FieldNumber) {
  PFriendCount_FieldNumber_Count = 1,
};

@interface PFriendCount : GPBMessage

/// 好友数量
@property(nonatomic, readwrite) int64_t count;

@end

#pragma mark - PSearchUser

typedef GPB_ENUM(PSearchUser_FieldNumber) {
  PSearchUser_FieldNumber_IsFriend = 1,
  PSearchUser_FieldNumber_IsFollowing = 2,
  PSearchUser_FieldNumber_User = 7,
};

/// 搜索用户信息
@interface PSearchUser : GPBMessage

/// 是否已经是好友
@property(nonatomic, readwrite) BOOL isFriend;

/// 是否已经申请好友
@property(nonatomic, readwrite) BOOL isFollowing;

///保留3~6用于扩展
@property(nonatomic, readwrite, strong, null_resettable) PUser *user;
/// Test to see if @c user has been set.
@property(nonatomic, readwrite) BOOL hasUser;

@end

#pragma mark - PSearchUserList

typedef GPB_ENUM(PSearchUserList_FieldNumber) {
  PSearchUserList_FieldNumber_SearchUsersArray = 1,
};

/// 搜索用户返回列表
@interface PSearchUserList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PSearchUser*> *searchUsersArray;
/// The number of items in @c searchUsersArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger searchUsersArray_Count;

@end

#pragma mark - PIsFriendList

typedef GPB_ENUM(PIsFriendList_FieldNumber) {
  PIsFriendList_FieldNumber_IsFriendArray = 1,
};

/// 是否是好友信息列表
@interface PIsFriendList : GPBMessage

/// 是否是好友
@property(nonatomic, readwrite, strong, null_resettable) GPBBoolArray *isFriendArray;
/// The number of items in @c isFriendArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger isFriendArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
